name: Release to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'debs/**'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if path is excluded
        id: check_path
        run: |
          if [[ $(git diff --name-only HEAD~1..HEAD) == *'debs/'* ]]; then
            echo "::set-output name=skip::true"
          else
            echo "::set-output name=skip::false"
          fi

      - name: Skip workflow if path is excluded
        if: steps.check_path.outputs.skip == 'true'
        run: echo "The workflow was skipped because changes were made in the excluded folder."

      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
